### PR TITLE
Small Tweaks

### PR DESCRIPTION
**Pull request by vbfox**
Small things I noticed while discovering the project a little bit.

* 2 Typos
* Suppress FS2003 warning (`An System.Reflection.AssemblyInformationalVersionAttribute specified version 'xxx', but this value is invalid and has been ignored`)

### CODE REVIEW

**Comment by 7sharp9** [comment]
Thanks!  Theres a refactor coming for the Fleece generation so Im glad this came before surfing a merge conflict :-)

**Comment by vbfox** [comment]
I'll need to look at that :)

I'm currently looking at serialization libraries for my workplace that would start from proto definition files and it seem that it might go either falanx or google protobuf (Compiling in a separate C# project and using from F#). I might do some contributions as part of that but it'll need the corporate CLA in place, what would be the procedure for it ?

**Comment by 7sharp9** [comment]
Dunno about the CLA, I just signed it as me :-)

**Comment by enricosada** [comment]
thank you you @vbfox !

**Pull request merged**
