### PR TITLE
Add missing paket.exe

### PR DESCRIPTION
**Pull request by panesofglass**
This will allow the build in the README to succeed.

### CODE REVIEW

**Comment by 7sharp9** [comment]
Yeah I forgot `.gitignore` dropped the magic mode bootstrapper from that directory, is this bin the bootstrapper renamed?

**Comment by panesofglass** [comment]
@7sharp9 yes, and feel free to just redo what I did here. I haven't received permission to sign the CLA as yet.

**Comment by gusty** [comment]
@panesofglass Are you unable to sign the CLA ?

If so let me know, I think for small changes like this it's normally not required.

**Comment by 7sharp9** [comment]
Thanks @panesofglass  I just added this in another PR, hopefully the CLA can be signed and you can help out with other bits and pieces! :-)

**Pull request closed without merging**
